### ISSUE TITLE
Precision lookup failure produces no toast: response.error.charAt throws first

### ISSUE THREAD

**Issue by MathijsBok** [klever-io/kleverscan#683]
`getPrecisionFromApi` in `src/utils/precisionFunctions/index.ts` means to warn the user when the precisions endpoint fails, but the warning never appears on transport-level failures.

```ts
if (response.error) {
  const messageError =
    response.error.charAt(0).toUpperCase() + response.error.slice(1);
  toast.error(messageError, { toastId: 'Fetch timeout' });
  throw new Error(response.error);
}
```

`response.error` is only a string when the API returned a JSON error body. On a network failure or a timeout, `src/services/api.ts` puts the caught `Error` object into `error` instead. `charAt` is then not a function, so line 115 throws a `TypeError` before `toast.error` on line 116 ever runs.

Measured with `assets/precisions` blocked at the network layer: console shows `TypeError: response.error.charAt is not a function at getPrecisionFromApi`, and no toast is rendered.

**Why it matters**

Every caller of `getPrecision` relies on this being the only user-visible signal that precisions could not be resolved. Without it the failure is completely silent, and the caller's fallback behaviour (whatever it is) looks like normal operation.

This is what made the block page failure in #680 hard to notice: the tab reported "Oops! Apparently no data here." on a block that demonstrably had transactions, with nothing in the UI to say why.

**Fix**

Normalise the error before formatting, e.g. take `String(response.error?.message ?? response.error)`, and guard the capitalisation against an empty string. Worth checking the other `response.error` string operations in the same module for the same assumption.

Found during the review for #680, outside that PR's diff.
